<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	  <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
	  <LangVersion>12.0</LangVersion>
	  <OutputType>WinExe</OutputType>
    <RootNamespace>Mids_Reborn</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
	  <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <Optimize>true</Optimize>
	  <NoWarn>CS1690, CS0169, CA1823, CA2213, CA1416</NoWarn>
	  <DebugType>full</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <Optimize>true</Optimize>
    <NoWarn>CS1690, CS0169, CA1823, CA2213, CA1416</NoWarn>
    <DebugType>full</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <NoWarn>1701;1702;CA1416</NoWarn>
    <DebugType>full</DebugType>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>MRB_Icon_Concept.ico</ApplicationIcon>
  </PropertyGroup>
  <PropertyGroup>
    <StartupObject>Mids_Reborn.Program</StartupObject>
  </PropertyGroup>
  <PropertyGroup>
	<AccelerateBuildsInVisualStudio>false</AccelerateBuildsInVisualStudio>
  </PropertyGroup>
  <ItemGroup>
    <Compile Update="Resources.en-US.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.en-US.resx</DependentUpon>
    </Compile>
    <Compile Update="UI\Controls\AdvGroupBox.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="UI\Controls\AdvListView.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="UI\Controls\BorderPanel.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="UI\Controls\BrightnessSelector.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="UI\Controls\ColorSlider.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="UI\Controls\ColorWheel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="UI\Controls\ctlColorList.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="UI\Controls\ctlCombatTimeline.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="UI\Controls\ctlDamageDisplay.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="UI\Controls\ctlDataGraph.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="UI\Controls\ctlEnhPicker.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="UI\Controls\ctlListViewColored.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="UI\Controls\ctlLockedTextBox.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="UI\Controls\ctlMultiGraph.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="UI\Controls\ctlOutlinedLabel.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="UI\Controls\ctlPanel.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="UI\Controls\ctlPopUp.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="UI\Controls\ctlPowerButton.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="UI\Controls\ctlPowerList.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="UI\Controls\ctlProgressBar.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="UI\Controls\ctlTotalsTabStrip.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="UI\Controls\DataView.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="UI\Forms\EditableLabel.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="UI\Controls\EnhCheckMode.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="UI\Controls\EnhPicker.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="UI\Controls\EnhSetInfo.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="UI\Forms\FileMover.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="UI\Controls\FilterableListBox.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="UI\Controls\FormPages.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="UI\Controls\GenericSelector.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="UI\Controls\GFXLabel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="UI\Controls\I9Picker.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="UI\Controls\ImageButton.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="UI\Controls\ImageButtonEx.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="UI\Forms\InputBox.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="UI\Controls\LabelEx.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="UI\Controls\ListLabel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="UI\Forms\MessageBoxEx.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="UI\Controls\MidsComboBox.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="UI\Controls\MidsMenuStrip.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="UI\Controls\NavStrip.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="UI\Controls\Page.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="UI\Controls\PairedList.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="UI\Controls\PairedListEx.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="UI\Controls\PanelGfx.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="UI\Forms\PerPixelAlpha.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="UI\Controls\PetView.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="UI\Forms\PowerSelector.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="UI\Controls\ProgressBarEx.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="UI\Controls\ScrollPanelEx.cs" />
    <Compile Update="UI\Controls\SwitchButton.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="UI\Controls\TimelineCursorZoom.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Content Include="Databases\Generic\Example UpdateManifest.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Homecoming\Images\*\*.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Homecoming\Images\*.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Rebirth\Images\*\*.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Rebirth\Images\*.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\*\*.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\*.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Rebirth\SData.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Fonts\DejaVuSansMono-Bold.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Fonts\DejaVuSansMono-BoldOblique.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Fonts\DejaVuSansMono-Oblique.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Fonts\DejaVuSansMono.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Fonts\NotoSans-Black.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Fonts\NotoSans-BlackItalic.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Fonts\NotoSans-Bold.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Fonts\NotoSans-BoldItalic.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Fonts\NotoSans-ExtraBold.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Fonts\NotoSans-ExtraBoldItalic.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Fonts\NotoSans-ExtraLight.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Fonts\NotoSans-ExtraLightItalic.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Fonts\NotoSans-Italic.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Fonts\NotoSans-Light.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Fonts\NotoSans-LightItalic.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Fonts\NotoSans-Medium.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Fonts\NotoSans-MediumItalic.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Fonts\NotoSans-Regular.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Fonts\NotoSans-SemiBold.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Fonts\NotoSans-SemiBoldItalic.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Fonts\NotoSans-Thin.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Fonts\NotoSans-ThinItalic.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\MRBLoading.gif">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
	<Content Include="Assets\Unknown.png">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</Content>
    <Content Include="Databases\Homecoming\AttribMod.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Homecoming\GlobalMods.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Homecoming\NLevels.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Homecoming\RLevels.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Generic\bbcode.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Generic\Compare.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Generic\EClasses.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Generic\EnhDB.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Generic\I12.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Generic\I9.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Generic\Maths.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Generic\NLevels.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Generic\Origins.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Generic\Recipe.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Generic\RLevels.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Generic\Salvage.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Generic\AttribMod.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Generic\GlobalMods.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Generic\TypeGrades.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="MRB_Icon_Concept.ico" />
    <Content Include="Databases\Generic\PowersReplTable.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Generic\SData.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Homecoming\PowersReplTable.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
	<Content Include="Databases\Homecoming\CrypticPowerNames.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Rebirth\AttribMod.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Rebirth\bbcode.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Rebirth\Compare.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Rebirth\EClasses.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Rebirth\EnhDB.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Rebirth\GlobalMods.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Rebirth\I12.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Rebirth\I9.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Rebirth\Maths.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Rebirth\NLevels.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Rebirth\Origins.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Rebirth\PowersReplTable.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Rebirth\Recipe.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Rebirth\RLevels.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Rebirth\Salvage.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Homecoming\TypeGrades.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Rebirth\TypeGrades.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Homecoming\SData.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Rebirth\SData.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <None Include="..\MRBResourceLib\Resources.resx" Link="Resources.resx">
      <Generator>None</Generator>
      <CustomToolNamespace>MRBResourceLib</CustomToolNamespace>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Content Include="Assets\Archetypes\Class_Arachnos_Soldier.png" />
    <Content Include="Assets\Archetypes\Class_Arachnos_Widow.png" />
    <Content Include="Assets\Archetypes\Class_Blaster.png" />
    <Content Include="Assets\Archetypes\Class_Boss_Henchman.png" />
    <Content Include="Assets\Archetypes\Class_Brute.png" />
    <Content Include="Assets\Archetypes\Class_Controller.png" />
    <Content Include="Assets\Archetypes\Class_Corruptor.png" />
    <Content Include="Assets\Archetypes\Class_Defender.png" />
    <Content Include="Assets\Archetypes\Class_Dominator.png" />
    <Content Include="Assets\Archetypes\Class_Lt_Henchman.png" />
    <Content Include="Assets\Archetypes\Class_Mastermind.png" />
    <Content Include="Assets\Archetypes\Class_Minion_Henchman.png" />
    <Content Include="Assets\Archetypes\Class_Minion_Pets.png" />
    <Content Include="Assets\Archetypes\Class_Peacebringer.png" />
	<Content Include="Assets\Archetypes\Class_Sentinel.png" />
    <Content Include="Assets\Archetypes\Class_Scrapper.png" />
    <Content Include="Assets\Archetypes\Class_Stalker.png" />
    <Content Include="Assets\Archetypes\Class_Tanker.png" />
    <Content Include="Assets\Archetypes\Class_Warshade.png" />
    <Content Include="Assets\Origins\Magic.png" />
    <Content Include="Assets\Origins\Mutation.png" />
    <Content Include="Assets\Origins\Natural.png" />
    <Content Include="Assets\Origins\Science.png" />
    <Content Include="Assets\Origins\Technology.png" />
  </ItemGroup>
  <ItemGroup>
    <WCFMetadata Include="Connected Services\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MRBLogging\MRBLogging.csproj" />
    <ProjectReference Include="..\MRBResourceLib\MRBResourceLib.csproj" />
    <ProjectReference Include="..\MRB_Boostrap\MRB_Boostrap.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Databases\Homecoming\bbcode.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Homecoming\Compare.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Homecoming\EClasses.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Homecoming\EnhDB.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Homecoming\I12.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Homecoming\I9.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Homecoming\Maths.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Homecoming\Origins.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Homecoming\Recipe.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Databases\Homecoming\Salvage.mhd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Costura.Fody" Version="6.0.0">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="FastDeepCloner">
      <Version>1.3.6</Version>
    </PackageReference>
    <PackageReference Include="Fody" Version="6.9.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="FontAwesome.Sharp">
      <Version>6.6.0</Version>
    </PackageReference>
    <PackageReference Include="Jace4fc" Version="1.0.2" />
    <PackageReference Include="Microsoft.Web.WebView2">
      <Version>1.0.3065.39</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.WinForms.Designer.SDK" Version="1.9.0-preview.3.24054.5" />
    <PackageReference Include="Newtonsoft.Json">
      <Version>13.0.3</Version>
    </PackageReference>
    <PackageReference Include="RestSharp">
      <Version>112.1.0</Version>
    </PackageReference>
    <PackageReference Include="RestSharp.Serializers.NewtonsoftJson">
      <Version>112.1.0</Version>
    </PackageReference>
    <PackageReference Include="SharpZipLib" Version="1.4.2" />
    <PackageReference Include="SkiaSharp" Version="3.116.1" />
    <PackageReference Include="SkiaSharp.Views" Version="3.116.1" />
    <PackageReference Include="SkiaSharp.Views.Desktop.Common" Version="3.116.1" />
    <PackageReference Include="SkiaSharp.Views.WindowsForms" Version="3.116.1" />
    <PackageReference Include="zlib.net-mutliplatform" Version="1.0.8" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Databases\Homecoming\Images\Classes\" />
    <Folder Include="Databases\Rebirth\Images\Classes\" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="UI\Forms\OptionsMenuItems\frmAttribModImporter.cs" />
    <Compile Remove="UI\Forms\OptionsMenuItems\frmAttribModImporter.Designer.cs" />
    <Compile Remove="GlobalSuppressions.cs" />
    <Content Remove="Assets\unlocked.png" />
    <EmbeddedResource Remove="frmImport_Powerset.resx" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Databases\Rebirth\SData.json" />
    <None Remove="Fonts\DejaVuSansMono-Bold.ttf" />
    <None Remove="Fonts\DejaVuSansMono-BoldOblique.ttf" />
    <None Remove="Fonts\DejaVuSansMono-Oblique.ttf" />
    <None Remove="Fonts\DejaVuSansMono.ttf" />
    <None Remove="Fonts\NotoSans-Black.ttf" />
    <None Remove="Fonts\NotoSans-BlackItalic.ttf" />
    <None Remove="Fonts\NotoSans-Bold.ttf" />
    <None Remove="Fonts\NotoSans-BoldItalic.ttf" />
    <None Remove="Fonts\NotoSans-ExtraBold.ttf" />
    <None Remove="Fonts\NotoSans-ExtraBoldItalic.ttf" />
    <None Remove="Fonts\NotoSans-ExtraLight.ttf" />
    <None Remove="Fonts\NotoSans-ExtraLightItalic.ttf" />
    <None Remove="Fonts\NotoSans-Italic.ttf" />
    <None Remove="Fonts\NotoSans-Light.ttf" />
    <None Remove="Fonts\NotoSans-LightItalic.ttf" />
    <None Remove="Fonts\NotoSans-Medium.ttf" />
    <None Remove="Fonts\NotoSans-MediumItalic.ttf" />
    <None Remove="Fonts\NotoSans-Regular.ttf" />
    <None Remove="Fonts\NotoSans-SemiBold.ttf" />
    <None Remove="Fonts\NotoSans-SemiBoldItalic.ttf" />
    <None Remove="Fonts\NotoSans-Thin.ttf" />
    <None Remove="Fonts\NotoSans-ThinItalic.ttf" />
    <None Remove="Assets\MRBLoading.gif" />
    <None Remove="Assets\unlocked.png" />
    <None Remove="MidsReborn.csproj.old" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appSettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Databases\blank.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Sythlin_DPS_Tool.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <PropertyGroup Label="Globals">
    <WebView2LoaderPreference>Static</WebView2LoaderPreference>
    <WV2WinRTVerbosity>low</WV2WinRTVerbosity>
  </PropertyGroup>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <UseWPF>False</UseWPF>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <NoWarn>1701;1702;CA1416</NoWarn>
    <DebugType>full</DebugType>
  </PropertyGroup>
	    <PropertyGroup>
        <Main>bin\$(Platform)\$(Configuration)\net6.0-windows\</Main>
		<Osx>bin\$(Platform)\$(Configuration)\net6.0-windows\runtimes\osx</Osx>
		<Win86>bin\$(Platform)\$(Configuration)\net6.0-windows\runtimes\win-x86</Win86>
        <WinARM>bin\$(Platform)\$(Configuration)\net6.0-windows\runtimes\win-arm64</WinARM>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
	</PropertyGroup>

	<Target Name="DeleteFilesAfterBuild" AfterTargets="Build">
		<ItemGroup>
			<FilesToDelete Include="$(Main)*Wpf.dll" />
		</ItemGroup>
		<Message Text="Deleting Files @(FilesToDelete)" />
		<Delete Files="@(FilesToDelete)">
			<Output TaskParameter="DeletedFiles" ItemName="FilesDeleted" />
		</Delete>
		<Message Text="Files deleted: @(FilesDeleted)" />
	</Target>

	<Target Name="DeleteFoldersAfterBuild" AfterTargets="DeleteFilesAfterBuild">
		<RemoveDir Directories="$(Osx)" />
		<RemoveDir Directories="$(Win86)" />
		<RemoveDir Directories="$(WinARM)" />
	</Target>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
	  <Exec Command="set Out=$(TargetDir)&#xD;&#xA;&#xD;&#xA;move /y &quot;%25Out%25MRBBootstrap.exe&quot;                &quot;%25Out%25New_MRBBootstrap.exe&quot;&#xD;&#xA;move /y &quot;%25Out%25MRBBootstrap.dll&quot;                &quot;%25Out%25New_MRBBootstrap.dll&quot;&#xD;&#xA;move /y &quot;%25Out%25MRBBootstrap.pdb&quot;                &quot;%25Out%25New_MRBBootstrap.pdb&quot;&#xD;&#xA;move /y &quot;%25Out%25MRBBootstrap.runtimeconfig.json&quot; &quot;%25Out%25New_MRBBootstrap.runtimeconfig.json&quot;&#xD;&#xA;move /y &quot;%25Out%25MRBBootstrap.deps.json&quot;          &quot;%25Out%25New_MRBBootstrap.deps.json&quot;" />
	</Target>						
</Project>